export type FieldCategory = 'basic' | 'logistics' | 'financial' | 'product' | 'other'
export type FieldFormat = 'currency' | 'percentage' | 'date' | 'status' | 'text' | 'number' | 'rate'

export interface TableSchema {
  tableId: string
  tableName: string
  fields: FieldSchema[]
  syncedAt: string
}

export interface FieldSchema {
  fieldId: string
  fieldName: string
  dataKey: string
  fieldType: number
  uiType: string
  isPrimary: boolean
  isExtend: boolean
  /** 飞书字段配置，由系统管理/同步设置同步得到；公式字段可含 formula/expression 等 */
  property?: Record<string, unknown>
  // Extended metadata for unified data layer
  category?: FieldCategory
  format?: FieldFormat
  priority?: number
  displayName?: string
}

export interface MappedFieldSchema extends FieldSchema {
  category: FieldCategory
  format: FieldFormat
  priority: number
  displayName: string
}

export interface TableSchemaStats {
  totalFields: number
  fieldsByCategory: Record<FieldCategory, number>
  fieldsByFormat: Record<FieldFormat, number>
  mappedFields: number
  autoGeneratedFields: number
}
